apiVersion: v1
kind: Service
metadata:
  name: streamforge-service
spec:
  type: NodePort
  selector:
    app: streamforge
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001 # Port fixe demandé (Mission 3.3)